version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: icecream-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  icecream-app:
    build: .
    container_name: icecream-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongodb_data: