apiVersion: v1
kind: Service
metadata:
  name: icecream-app-service
  labels:
    app: icecream-app
spec:
  type: NodePort
  selector:
    app: icecream-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000  # External access port
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  type: ClusterIP  # Internal service only